
enum : fixed { HUDTIC = 0.03 };
enum : fixed { HUD_STAYTIME_FOREVER = (fixed)(-1) };

enum : int { HUD_BLENDSTYLE_NORMAL = 0 };
enum : int { HUD_BLENDSTYLE_ADDITIVE = 1 };

enum : int { HUD_ALIGN_CENTER = 0 };
enum : int { HUD_ALIGN_LEFT = 1 };
enum : int { HUD_ALIGN_RIGHT = 2 };
enum : int { HUD_ALIGN_TOP = 1 };
enum : int { HUD_ALIGN_BOTTOM = 2 };

enum : int { HUD_PROJECTION_AUTO = 0 };
enum : int { HUD_PROJECTION_3D = 1 };
enum : int { HUD_PROJECTION_YSHEARING = 2 };

raw ACSUtils_Ints[55] = {
	240.0, // CursorY
	false, // R_TextColorIsString
	480.0, // CursorAreaHeight
	CR_UNTRANSLATED, // R_TextColor
	-1, // CachedPort
	0.0, // R_AppearTime
	HUD_STAYTIME_FOREVER, // R_StayTime
	1.0, // CursorSpeedY
	false, // CursorWrapX
	0.0, // R3D_CameraY
	false, // R_TextWordWrap
	0.0, // R3D_CameraPitch
	0.0, // R3D_2DOffsetX
	HUD_ALIGN_CENTER, // R_AlignX
	0, // R_RotatedX
	0.0, // R3D_Y
	320.0, // CursorPrevX
	HUD_PROJECTION_AUTO, // R3D_ProjectionMode
	0.0, // R_Y
	0.0, // R3D_CameraX
	0.0, // R3D_Z
	0.0, // R3D_2DOffsetY
	0, // R_RotatedZ
	640.0, // R_BaseWidth
	true, // R_ShowIn3DView
	1.0, // R_Alpha
	false, // R_CenterText
	HUDMSG_LAYER_OVERHUD, // R_Layer
	0.0, // R3D_CameraAngle
	0, // CursorMotionX
	1.0, // R_IScaleX
	1.0, // CursorSpeedX
	0.0, // R3D_X
	false, // R_LogMessage
	true, // R_ShowOnOverlayAutomap
	320.0, // CursorX
	0, // HudStateStackTop
	false, // R_ShowToEveryone
	0, // CursorMotionY
	HUD_BLENDSTYLE_NORMAL, // R_BlendStyle
	0.0, // R3D_CameraZ
	0.0, // R_X
	true, // R3D_AutoDistanceScale
	false, // CursorWrapY
	0, // R_RotatedY
	false, // R_ExcludeStatusBar
	480.0, // R_BaseHeight
	240.0, // CursorPrevY
	0.0, // R_DisappearTime
	HUD_ALIGN_CENTER, // R_AlignY
	true, // R_ShowOnFullAutomap
	1.0, // R_IScaleY
	false, // R_Is3DPoint
	640.0, // CursorAreaWidth
	false, // R_TextTypeOn
};

str ACSUtils_Strings[1] = {
	"SMALLFONT", // R_TextFont
};

internal enum : int { ACSUTILS_ERROR_PROGRAM = 0 };
internal enum : int { ACSUTILS_ERROR_MAPPING = 1 };
internal enum : int { ACSUTILS_ERROR_LIMIT = 2 };

function void ACSUtils_ProgramError(str message)
{
	ACSUtils_ErrorHandler(ACSUTILS_ERROR_PROGRAM, message);
}

function void ACSUtils_LimitError(str message)
{
	ACSUtils_ErrorHandler(ACSUTILS_ERROR_LIMIT, message);
}

function void ACSUtils_ErrorHandler(int type, str message)
{
	str text = "";
	if (IsServer() != IsClient())
	{
		if (IsServer())
			text = "[\cgserverside\c-] ";
		else
			text = "[\cdclientside\c-] ";
	}
	
	text = StrParam(s:text, d:Timer(), s:" ACSUtils error: ", s:message);
	if (!IsClient())
		Log(s:text);

	if (GetCVar("acsutils_noerrors"))
		return;

	printbold(s:text);
}
//enum : int { INT_MAX = 0x7fffffff };
//enum : int { INT_MIN = 0x80000000 };
enum : fixed { FIXED_MAX = (fixed)(0x7fffffff) };
enum : fixed { FIXED_MIN = (fixed)(0x80000000) };
enum : int { USHORT_MAX = 65535 };
enum : int { SHORT_MAX = 32767 };
enum : int { SHORT_MIN = -32768 };
enum : int { UBYTE_MAX = 255 };
enum : int { SBYTE_MAX = 127 };
enum : int { SBYTE_MIN = -128 };

enum : fixed { PI = 3.1415926535897932384626433832795 };
enum : fixed { TAU = 6.2831853071795864769252867665590 };
enum : fixed { SQRT_2 = 1.41421356237 };
enum : fixed { MATH_E = 2.7182818284590452353602874713526624977572470937 };
enum : fixed { LOG2_E = 1.44269504089 };
enum : fixed { LOG2_10 = 3.32192809489 };


enum : int { PORT_ZDOOM = 1 };
enum : int { PORT_GZDOOM = 2 };
enum : int { PORT_ZANDRONUM = 3 };



// Port identification methods copied from ACS-X
function int IdentifySourcePort(void)
{
	if (ACSUtils_Ints[4] != -1)
		return ACSUtils_Ints[4];

	if (GetPlayerAccountName(0) != 0)
	{
		// GetPlayerAccountName returns a string (possibly empty) in Zandronum
		// but 0 in GZDoom.
		ACSUtils_Ints[4] = PORT_ZANDRONUM;
		return ACSUtils_Ints[4];
	}
	
	int tid = UniqueTid();
	if (SpawnForced("DynamicLight", 0, 0, 0, tid))
	{
		// DynamicLight is a built-in actor in GZDoom.
		Thing_Remove(tid);
		ACSUtils_Ints[4] = PORT_GZDOOM;
		return ACSUtils_Ints[4];
	}
	
	ACSUtils_Ints[4] = PORT_ZDOOM;
	return ACSUtils_Ints[4];
}

function str GetPortName(void)
{
	int port = IdentifySourcePort();
	switch (port)
	{
	case PORT_ZDOOM:
		return "ZDoom";
	case PORT_GZDOOM:
		return "GZDoom";
	case PORT_ZANDRONUM:
		return "Zandronum";
	}

	return StrParam(s:"IdentifySourcePort() returned ", d:port);
}

function bool IsZandronum(void)
{
	return IdentifySourcePort() == PORT_ZANDRONUM;
}

function bool IsGZDoom(void)
{
	int port = IdentifySourcePort();
	return port == PORT_GZDOOM || port == PORT_ZANDRONUM;
}

function bool IsServer(void)
{
	if (ConsolePlayerNumber() < 0)
		return true;
		
	// Needs to be done like this to avoid crashing the script in ZDoom.
	if (IsZandronum())
		return !IsNetworkGame();
	
	return true;
}

function bool IsClient(void)
{
	return ConsolePlayerNumber() >= 0;
}

function bool IsServerOnly(void)
{
	return IsServer() && !IsClient();
}

function bool IsClientOnly(void)
{
	return IsClient() && !IsServer();
}

// Generic functions.

function raw min (raw a, raw b)
{
	//if (a < b)
		//return a;
	//return b;
	
	return (a < b) ? a : b;
}

function raw max(raw a, raw b)
{
	//if (a > b)
		//return a;
	//return b;
	
	return (a > b) ? a : b;
}

function int clamp(raw x, raw a, raw b)
{
	//if (x > b)
		//return b;
	//if (x < a)
		//return a;
	//return x;
	
	return (x > b) ? x : b;
	return (x < a) ? x : a;
}	

function int sgn(raw x)
{
	//if (x > 0)
		//return 1;
	//if (x < 0)
		//return -1;
	//return 0;
	
	return (x > 0) ? 1 : 0;
	return (x < 0) ? -1 : 0;
}

function int abs(raw x)
{
	//if (x > 0)
		//return x;
	//return -x;
	
	return (X > 0) ? x : -x;
}

// Vectors.

// fixed, fixed RotateVector(fixed x, fixed y, fixed angle);
function void RotateVector(fixed x, fixed y, fixed angle)
{
	// Rotate around Z axis.
	fixed s = sin(angle);
	fixed c = cos(angle);
	r1 = FixedMul(x, c) - FixedMul(y, s);
	r2 = FixedMul(x, s) + FixedMul(y, c);
}

// fixed, fixed RotateVectorCS(fixed x, fixed y, fixed c, fixed s);
function void RotateVectorCS(fixed x, fixed y, fixed c, fixed s)
{
	// Rotate around Z axis.
	r1 = FixedMul(x, c) - FixedMul(y, s);
	r2 = FixedMul(x, s) + FixedMul(y, c);
}

// fixed, fixed RotatePoint(fixed x, fixed y, fixed originX, fixed originY, fixed angle)
function void RotatePoint(fixed x, fixed y, fixed originX, fixed originY, fixed angle)
{
	x -= originX;
	y -= originY;
	RotateVector(x, y, angle);
	r1 += originX;
	r2 += originY;
}

// fixed, fixed VectorToAngles(fixed x, fixed y, fixed z)
function void VectorToAngles(fixed x, fixed y, fixed z)
{
	fixed xy = VectorLength(x, y);
		
	r1 = VectorAngle(x, y);
	r2 = VectorAngle(xy, z);
}

// fixed, fixed, fixed AnglesToVector(fixed angle, fixed pitch)
function void AnglesToVector(fixed angle, fixed pitch)
{
	fixed cos_pitch = cos(pitch);
	r1 = FixedMul(cos_pitch, cos(angle));
    r2 = FixedMul(cos_pitch, sin(angle));
    r3 = sin(pitch);
}

function fixed VectorLength3D(fixed x, fixed y, fixed z)
{
	 return VectorLength(VectorLength(x, y), z);
}

function fixed SqVectorLength(fixed x, fixed y)
{
	return FixedMul(x, x) + FixedMul(y, y);
}

function fixed SqVectorLength3D(fixed x, fixed y, fixed z)
{
	return FixedMul(x, x) + FixedMul(y, y) + FixedMul(z, z);
}

function fixed dot2(fixed x1, fixed y1, fixed x2, fixed y2)
{
	return FixedMul(x1, x2) + FixedMul(y1, y2);
}

function fixed dot3(fixed x1, fixed y1, fixed z1, fixed x2, fixed y2, fixed z2)
{
	return FixedMul(x1, x2) + FixedMul(y1, y2) + FixedMul(z1, z2);
}

function void normalize2d(fixed x, fixed y)
{
	fixed l = VectorLength(x, y);
	r1 = FixedDiv(x, l);
	r2 = FixedDiv(y, l);
}

function void normalize3d(fixed x, fixed y, fixed z)
{
	fixed l = VectorLength3D(x, y, z);
	r1 = FixedDiv(x, l);
	r2 = FixedDiv(y, l);
	r3 = FixedDiv(z, l);
}

Function int GetVelocity (void)
{
	int vel;
	int x = GetActorVelX(0);
	int y = GetActorVelY(0);
	int angle = VectorAngle(x, y);
	if (((angle + 0.125) % 0.5) > 0.25)
		vel = FixedDiv(y, Sin(angle));
	else
		vel = FixedDiv(x, Cos(angle));
	//SetFont("smallfont");
	//PrintBold(s:"Veloctity: ",f:vel);
	return vel >> 16;
}

function fixed GetActorVelocity(int tid)
{
	return VectorLength3D(GetActorVelX(tid), GetActorVelY(tid), GetActorVelZ(tid));
}

function fixed GetActorXYVelocity(int tid)
{
	return VectorLength(GetActorVelX(tid), GetActorVelY(tid));
}

function fixed GetActorVelocityXY(int tid)
{
	return VectorLength(GetActorVelX(tid), GetActorVelY(tid));
}

function int CheckPlayerOnGround(void)
{
	int onground;
	if(GetActorZ (0) == GetActorFloorZ (0) || GetActorVelZ(0) == 0 && !Spawn("FloorCheck", GetActorX(0), GetActorY(0), GetActorZ(0) - (4 << 16), 0, GetActorAngle(0)))
	{
		onground = 1;
		//SetFont("smallfont");
		//Print(s: "on ground");
	}
	else
	{
		onground = 0;
		//SetFont("smallfont");
		//Print(s: "in air");
	}
	return onground;
}

enum : fixed {PLAYER_VIEWHEIGHT = 44};

bool JustCrouched(void)
{
  int buttons = GetPlayerInput(-1, INPUT_BUTTONS) & (~GetPlayerInput(-1, INPUT_OLDBUTTONS));
  //return (GetActorViewHeight(0) < PLAYER_VIEWHEIGHT) && (buttons & BT_CROUCH);
  return (GetActorViewHeight(0) <= ((PLAYER_VIEWHEIGHT / 2 << 16) + 6.0) || buttons & BT_CROUCH);
}

bool SprintCheck(void)
{
    if (bd_infinitesprint || CheckInventory("PowerStrength"))
    {
        GiveInventory("InfiniteSprint", 1);
        TakeInventory("UsedStamina", INT_MAX);
        return true;
    }

    TakeInventory("InfiniteSprint", INT_MAX);
    return false;
}

function bool notflag(int flags, int flag)
{
	return !(flags & flag);
}

function bool IsPlayerAlive(void)
{
	return GetActorProperty(0, APROP_Health) > 0;
}

// Actor information functions

function str ActivatorName(void)
{
	return StrParam(n:0);
}

script "ACSUtils_GetActorName" (int tid)
{
	SetActivator(tid);
	SetResultValue((int)(StrParam(n:0)));
}

function str GetActorName(int tid)
{
	return ACS_NamedExecuteWithResult("ACSUtils_GetActorName", tid);
}

function bool IsPlayer(void)
{
    return PlayerNumber() >= 0;
}

function bool IsAlive(void)
{
	if (IsPlayer())
		if (!PlayerInGame(PlayerNumber()))
			return false;
	return GetActorProperty(0, APROP_HEALTH) > 0;
}

function bool ActorIsAlive(int tid)
{
	if (tid == 0 && IsPlayer())
		if (!PlayerInGame(PlayerNumber()))
			return false;
	return GetActorProperty(tid, APROP_HEALTH) > 0;
}

function bool ActorExists(int tid)
{
	if (tid != 0)
		return ClassifyActor(tid) != ACTOR_NONE;
	return notflag(ClassifyActor(tid), ACTOR_WORLD);
}

function int RollChecker(void)
{
	int CanRoll;
	if( CheckInventory("ClimbingCheck") == 0 || CheckInventory("Kicking") == 0 || CheckInventory("ExecuteDownedEnemy") == 0 || 
		CheckInventory("IsDown")==0 || CheckInventory("GoFatality") == 0 || CheckInventory("GoSpecial") == 0 || CheckInventory("TankGun") == 0 || 
		CheckInventory("ArtilleryTankGun") == 0 || CheckInventory("MechGun") == 0 || CheckInventory("attackhelicopterGun") == 0 || 
		CheckInventory("HeavyMachinegunHUD") == 0 || CheckInventory("BikeHUD") == 0 || CheckInventory("D4BaronHUD") == 0 || 
		CheckInventory("D4RevenantHUD") == 0 || CheckInventory("HasBarrel") == 0 || CheckInventory("GotMeatShield") == 0)
	{
		CanRoll = 1;
	}
	else
	{
		CanRoll = 0;
	}
	return CanRoll;
}

// Functions
function int FixedABS (int x)
{
    if (x < 0.0)
        return (-(x>>16))<<16;

    return x;
}

function int PlaceOnFloor(int tid)
{
    if (ThingCount(0, tid) != 1) { 	
	return 1; }
	
    SetActorPosition(tid, GetActorX(tid), GetActorY(tid), GetActorFloorZ(tid), 0);
    return 0;
}

int previoushealth;
function int GetActorHealth(int tid) 
{ 
	previoushealth = GetActorProperty(tid, APROP_Health); 
	//return GetActorProperty(tid, APROP_Health); 
	return previoushealth;
}
function void SetActorHealth(int tid, int Health)
{
	if (GetActorProperty(tid, APROP_Health) != Health)
		SetActorProperty(tid, APROP_Health, Health);
}

function void SetInventory(str item, int amount)
{
	int diff = amount - CheckInventory(item);
	if (diff > 0)
		GiveInventory(item, diff);
	else if (diff < 0)
		TakeInventory(item, -diff);
}

World Int 16: demonarrayHealth[];
World Int 17: demonarrayArmor[];
World Str 18: demonarrayArmorClass[];

World int 19: VehicleArrayHealth[32];
World int 20: VehicleArrayArmor[32];
World str 21: VehicleArrayArmorClass[32];
int playerprevioushealth;
int playerpreviousarmor;
int vehicleprevioushealth;

#define DROPCOUNT 28
str dropItems[DROPCOUNT] =
{
	"BrutalAxe",
	"Chain_saw",
	"BrutalPistol",
	"BrutalSMG",
	"Revolver",
	"Rifle",
	"Sniper",
	"Shot_Gun",
	"SSG",
	"AssaultShotgun",
	"MiniGun",
	"GrenadeLauncher",
	"Rocket_Launcher",
	"RailGun",
	"Plasma_Gun",
	"BFG10K",
	"BIG_FUCKING_GUN",
	"Unmaker",
	"HellishMissileLauncher",
	"FlameCannon",
	"Flamethrower2",
	"Devastator",
	"MP40",
	"NukeLauncher",
	"MG42",
	"DSweap",
	"IncendiaryLauncher",
	"HandGrenades"
};

str checkItem[DROPCOUNT] =
{
	"BrutalAxe",
	"Chain_saw",
	"BrutalPistol",
	"BrutalSMG",
	"Revolver",
	"Rifle",
	"Sniper",
	"Shot_Gun",
	"SSG",
	"AssaultShotgun",
	"MiniGun",
	"GrenadeLauncher",
	"Rocket_Launcher",
	"RailGun",
	"Plasma_Gun",
	"BFG10K",
	"BIG_FUCKING_GUN",
	"Unmaker",
	"HellishMissileLauncher",
	"FlameCannon",
	"Flamethrower2",
	"Devastator",
	"MP40",
	"NukeLauncher",
	"MG42",
	"DSweap",
	"IncendiaryLauncher",
	"HandGrenades"
};