// ACS

#define MAX_PLAYERS 64

#library "BD_Main"
#import "zcommon.bcs"

#if 1
#define HEAP_SIZE 1 // BD won't use malloc, so turn it off
#endif
#include "libbcs.bcs"

#include "BCSFunc.acs"
#include "BDMO_Monsters.acs"

// Server Variables (mirrors of the server cvars in CVARINFO.txt)
int zdoombrutalblood;
int zdoombrutaljanitor;
int isrunningzandronum;
int bd_classicmonsters;
int bd_AgileZombies;
int BD_DestructibleBodies;
int bd_WadCheck;
int BD_NOBOSSES;
int bd_zombiemanspawn;
int bd_shotgunguyspawn;

struct BD_CVarInfo
{
	// Client Variables
	int bd_bloodamount;

} BDCVarInfo[MAX_PLAYERS];

script "ServerCVars" OPEN
{
	zdoombrutaljanitor = GetCvar("zdoombrutaljanitor");
	zdoombrutalblood = GetCvar("zdoombrutalblood");
	isrunningzandronum = GetCvar("isrunningzandronum");
	bd_classicmonsters = GetCvar("bd_classicmonsters");
	bd_AgileZombies = GetCVAR("bd_AgileZombies");
	BD_DestructibleBodies = GetCvar("BD_DestructibleBodies");
	bd_WadCheck = GetCvar("bd_WadCheck");
	BD_NOBOSSES = GetCvar("BD_NOBOSSES");
	bd_zombiemanspawn = GetCvar("bd_zombiemanspawn");
	bd_shotgunguyspawn = GetCvar("bd_shotgunguyspawn");
	delay(1);
}

script "ClientCVars" ENTER
{
	BDCVarInfo[PlayerNumber()].bd_bloodamount = GetCvar("bd_bloodamount");
	delay(1);
}

script "GetCVars" (void) net
{
	delay(3);
	ACS_NamedExecuteAlways("ServerCVars", 0);
	ACS_NamedExecuteAlways("ClientCVars", 0);
}

//presets
script "DefaultCvars" (void) net
{
	SetCvar("bd_classicmonsters", 0);
	SetCvar("bd_AgileZombies", 0);
	SetCvar("BD_DestructibleBodies", 1);
	SetCvar("bd_WadCheck", 1);
	SetCvar("BD_NOBOSSES", 0);
	SetCvar("bd_zombiemanspawn", 1);
	SetCvar("bd_shotgunguyspawn", 1);
	ACS_NamedExecute("ServerCVars", 0);
	ACS_NamedExecute("ClientCVars", 0);
	delay(1);
}

script "AllCvarsOn" (void) net
{
	SetCvar("bd_classicmonsters", 0);
	SetCvar("bd_AgileZombies", 0);
	SetCvar("BD_DestructibleBodies", 1);
	SetCvar("bd_WadCheck", 1);
	SetCvar("BD_NOBOSSES", 0);
	SetCvar("bd_zombiemanspawn", 0);
	SetCvar("bd_shotgunguyspawn", 0);
	ACS_NamedExecute("ServerCVars", 0);
	ACS_NamedExecute("ClientCVars", 0);
	delay(1);
}

script "MinimalismCvars" (void) net
{
	SetCvar("bd_classicmonsters", 0);
	SetCvar("bd_AgileZombies", 0);
	SetCvar("BD_DestructibleBodies", 0);
	SetCvar("bd_WadCheck", 1);
	SetCvar("BD_NOBOSSES", 1);
	SetCvar("bd_zombiemanspawn", 1);
	SetCvar("bd_shotgunguyspawn", 1);
	ACS_NamedExecute("ServerCVars", 0);
	ACS_NamedExecute("ClientCVars", 0);
	delay(1);
}

script "PerformanceFriendlyCVARS" (void) net
{
	ACS_NamedExecute("ServerCVars", 0);
	ACS_NamedExecute("ClientCVars", 0);
	delay(1);
}
