// Eviternity Enhancements
//int WTHR;
Script "BD_ME_10632584414121315147" // ET_MAP01
{ 
	//WTHR = UniqueTID(); 
	//SpawnForced("Mapspot", -128.0, -672.0, 0.0, WTHR); 
	ACS_NamedExecute("TE_WeatherRain",0); 
}

Script "BD_ME_16687030840402216640" // ET_MAP02
{ 
	//WTHR = UniqueTID(); 
	//SpawnForced("Mapspot", 344.0, 120.0, 0.0, WTHR); 
	ACS_NamedExecute("TE_WeatherRain",0); 
}

Script "BD_ME_5811781407445932529" // ET_MAP03
{
	//WTHR = UniqueTID(); 
	//SpawnForced("Mapspot", -1472.0, 2112.0, 0.0, WTHR); 
	if(!GetPlayerAccountName(PlayerIsLoggedIn(playernumber())))
	{
		//Log(s:"GZDoom is Loaded");
		terminate;
	}
	else
	ACS_NamedExecute("TE_WeatherRain",0); 
}

Script "BD_ME_16736354090225434106" // ET_MAP04
{
	//WTHR = UniqueTID(); 
	//SpawnForced("Mapspot", -192.0, -992.0, 0.0, WTHR); 
	if(!GetPlayerAccountName(PlayerIsLoggedIn(playernumber())))
	{
		//Log(s:"GZDoom is Loaded");
		terminate;
	}
	else
	ACS_NamedExecute("TE_WeatherRain",0); 
}

Script "BD_ME_3860710824901000349" // ET_MAP11
{
	//WTHR = UniqueTID(); 
	//SpawnForced("Mapspot", 0.0, 32.0, 0.0, WTHR); 
	if(!GetPlayerAccountName(PlayerIsLoggedIn(playernumber())))
	{
		//Log(s:"GZDoom is Loaded");
		terminate;
	}
	else
	//Log(s:"Map11 IS indeed loaded..."); 
	ACS_NamedExecute("TE_WeatherSnow",0); 
}

Script "BD_ME_11258406434261716880" // ET_MAP12
{
	Spawn("DummySecret", -3904*65536, 1920*65536, 420*65536);
		
	SetLineSpecial(17, ACS_NamedLockedExecute, "EviMap12_1",0,0,0,0);
	SetLineSpecial(31, ACS_NamedLockedExecute, "EviMap12_2",0,0,0,0);
	SetLineSpecial(32, ACS_NamedLockedExecute, "EviMap12_3",0,0,0,0);
	SetLineSpecial(18, ACS_NamedLockedExecute, "EviMap12_4",0,0,0,0);
}

Script "BD_ME_16368823923043087197" // ET_MAP13
{
	//WTHR = UniqueTID(); 
	//SpawnForced("Mapspot", -2368.0, 256.0, 0.0, WTHR); 
	//Log(s:"Map13 IS indeed loaded..."); 
	if(!GetPlayerAccountName(PlayerIsLoggedIn(playernumber())))
	{
		//Log(s:"GZDoom is Loaded");
		terminate;
	}
	else
	ACS_NamedExecute("TE_WeatherSnow",0); 
}

Script "BD_ME_112112047450177432" // ET_MAP14
{
	//WTHR = UniqueTID(); 
	//SpawnForced("Mapspot", 544.0, -1248.0, 0.0, WTHR); 
	Spawn("Blocker2", 1664*65536, -5792*65536, 5*65536);
	Spawn("Blocker2", 2560*65536, -5792*65536, 5*65536);
	Spawn("Blocker2", 2944*65536, -5792*65536, 5*65536);
	Spawn("Blocker2", 4096*65536, -5792*65536, 5*65536);
	Spawn("Blocker2", 4608*65536, -5792*65536, 5*65536);
	Spawn("Blocker2", 4992*65536, -5792*65536, 5*65536);
	Spawn("Blocker2", -2880*65536, -5280*65536, 5*65536);
	Spawn("Blocker2", -1856*65536, -5280*65536, 5*65536);
	Spawn("Blocker2", -1088*65536, -5280*65536, 5*65536);
	Spawn("Blocker2", -448*65536, -5280*65536, 5*65536);
	Spawn("Blocker2", 896*65536, -5280*65536, 5*65536);
	if(!GetPlayerAccountName(PlayerIsLoggedIn(playernumber())))
	{
		//Log(s:"GZDoom is Loaded");
		terminate;
	}
	else
	ACS_NamedExecute("TE_WeatherSnow",0);
}

Script "BD_ME_9940356018446094831" // ET_MAP15
{
	//WTHR = UniqueTID(); 
	//SpawnForced("Mapspot", 2592.0, 2288.0, 0.0, WTHR); 
	if(!GetPlayerAccountName(PlayerIsLoggedIn(playernumber())))
	{
		//Log(s:"GZDoom is Loaded");
		terminate;
	}
	else
	ACS_NamedExecute("TE_WeatherSnow",0); 
}

Script "BD_ME_2508552849618885540" // ET_MAP19
{
	GiveInventory("PlayingEviternity", 1);
}

Script "BD_ME_9426870272125379381" // ET_MAP22
{
	Floor_RaiseByValue(43,1,10);
	Floor_RaiseByValue(43,1,10);
	Spawn("NightmareDemon", -64*65536, 		-1408*65536, 	5*65536);
	Spawn("NightmareDemon", 448*65536, 		-1568*65536, 	5*65536);
	Spawn("Blocker",		-256*65536,		-1504*65536,	5*65536,	1777);
	Spawn("Blocker",		288*65536,		-1504*65536,	5*65536,	1778);
	Spawn("TrapStarter",	-1536*65536,	-1024*65536,	5*65536,	1777);
}

Script "BD_ME_17796527272907971316" // ET_MAP26
{
	GiveInventory("PlayingEviternity", 1);
	GiveInventory("PlayingEviternityLastEpisode", 1);
}

Script "BD_ME_284836703899266438" // ET_MAP27
{
	GiveInventory("PlayingEviternity", 1);
	GiveInventory("PlayingEviternityLastEpisode", 1);
}

Script "BD_ME_176183746661336960" // ET_MAP28
{
	GiveInventory("PlayingEviternity", 1);
	GiveInventory("PlayingEviternityLastEpisode", 1);
}

Script "BD_ME_9195350410859572798" // ET_MAP29
{
	GiveInventory("PlayingEviternity", 1);
	GiveInventory("PlayingEviternityLastEpisode", 1);
}

Script "BD_ME_18302513185874783296" // ET_MAP30
{
	GiveInventory("PlayingEviternity", 1);
	GiveInventory("PlayingEviternityLastEpisode", 1);
	GiveInventory("LevelCounter", 4);
	Spawn("RevolverSpawner",	-1280*65536,	0,				20*65536);
	Spawn("ASGSpawner",			1280*65536,		0,				20*65536);
	Spawn("RailgunSpawner",		-640*65536,		1088*65536,		20*65536);
	Spawn("ChainsawSpawner",	640*65536,		1088*65536,		20*65536);
	Spawn("SMGSpawner",			-640*65536,		-1088*65536,	20*65536);
	Spawn("MG42",				640*65536,		-1088*65536,	20*65536);
	Spawn("Blocker",			4000*65536,		6112*65536,		5*65536,	777);
}


script "EviMap12_1" (void)
{
	//PrintBold(s:"Script 1");
	Ceiling_RaiseByValue(17,32,32);
	Delay(50);
	Ceiling_LowerByValue(17,32,32);
}
script "EviMap12_2" (void)
{
	//PrintBold(s:"Script 2");
	Ceiling_RaiseByValue(31,32,32);
	Delay(50);
	Ceiling_LowerByValue(31,32,32);
}
script "EviMap12_3" (void)
{
	//PrintBold(s:"Script 3");
	Ceiling_RaiseByValue(32,32,32);
	Delay(50);
	Ceiling_LowerByValue(32,32,32);
}
script "EviMap12_4" (void)
{
	//PrintBold(s:"Script 4");
	Ceiling_RaiseByValue(18,32,32);
	Delay(50);
	Ceiling_LowerByValue(18,32,32);
}

Script "TE_EviternityBossHealthbar" (VOID)
{
    //Let's write the Boss's name here.
	setfont("BIGFONT");
	HudMessageBold(s:"-= BOSS =-"; HUDMSG_PLAIN, 0, CR_RED, 1.5, 0.09, 0.1, 1.0);
	
	//How much health the boss currently has.
	setfont("SMALLFONT");
	int	bosshealth = GetActorProperty(0, APROP_Health);
	HudMessageBold(d:bosshealth; HUDMSG_PLAIN, 0, CR_WHITE, 1.43, 0.15, 0.1, 1.0);
	
	//Just a divider
	HudMessageBold(s:"/"; HUDMSG_PLAIN, 0, CR_WHITE, 1.5, 0.15, 0.05, 1.0);
	
	//The boss's max health.
	int	bossmaxhealth = GetActorProperty(0, APROP_SpawnHealth);
	HudMessageBold(d:bossmaxhealth; HUDMSG_PLAIN, 0, CR_WHITE, 1.57, 0.15, 0.1, 1.0);
	delay(1);
	
	//Check if the boss still is alive. If yes, repeat the script, if not, it ends here.
	if (GetActorProperty(0, APROP_Health)> 1)
	restart;
	//else
    //;
}

Script "TE_EviternityBossPhase2" (VOID)
{
	Spawn("U_ArchangelusB",0,0,138*65536);
}

Script "TE_EviternityBossPhase3" (VOID)
{
	int Monsters = GetLevelInfo(LEVELINFO_KILLED_MONSTERS);
	if (Monsters > 666)
	{
		SetActorState(0, "Spawn1");
		Delay(210);
		Spawn("AmmoSuply",			896*65536,		512*65536,		20*65536);
		Spawn("AmmoSuply",			896*65536,		-512*65536,		20*65536);
		Spawn("AmmoSuply",			-1056*65536,	0,				20*65536);
		//Spawn("BloodrushSphere",	0,				0,				20*65536);
		terminate;
	}
	Delay(35);
	restart;
}

Script "TE_EviternityBossTranslations" Open
{
	CreateTranslation (97, 160:167=192:207, 64:79=192:207, 48:79=192:207, 248:249=236:237);
}

Script "TE_EviternityBossColorChange" (VOID)
{
	Thing_SetTranslation(0, 97);
}

/*

Script "TE_OTEXtextures" ENTER //OTEX textures
{
ReplaceTextures("OBLODA01","BLOOD1");		//Blood					ok!
//ReplaceTextures("OGOOPY01","OGOOPY01");	//Purple water
//ReplaceTextures("OICYWA01","OICYWA01");	//Icy water
ReplaceTextures("OLAVAC01","LAVAFL");		//Lava					ok!
ReplaceTextures("OLAVAD01","LAVAFL");		//Yellow water			kinda ok
ReplaceTextures("ONUKEA01","SLIME01");		//Green water			ok!
ReplaceTextures("OSLUDG01","NUKAGE1");		//Dirty water			ok!
ReplaceTextures("OTAR__01","SLIME05");		//Mud					ok!
ReplaceTextures("OWATER01","FWATER1");		//Blue water			kinda ok

ReplaceTextures("OROCKL10","SLIME09");		//Lava cracked rocks

ReplaceTextures("OFALLB01","BFALL1");		//Blood fall			kinda ok
//ReplaceTextures("BLOOD1","BLOOD1");		//Purple waterfall
//ReplaceTextures("BLOOD1","BLOOD1");		//Icy waterfall
ReplaceTextures("OFALLL01","LFALL01");		//Lava fall				ok!
ReplaceTextures("OFALLM01","LFALL01");		//Yellow waterfall		kinda ok
ReplaceTextures("OFALLN01","CRFAL01");		//Green waterfall		ok!
//ReplaceTextures("OFALLS01","SFALL1");		//Dirty waterfall		not ok
//ReplaceTextures("OFALLT01","CRFAL01");	//Muddy waterfall		not ok
ReplaceTextures("OFALLW01","WFALL1");		//Blue waterfall		kinda ok
}

SMBTA	ShortBlueTorch
SMGTA	ShortGreenTorch
SMRTA	ShortRedTorch

TRE1A	TorchTree		grönt träd
TRE2A	BigTree			gran med snö
COL1A	TallGreenColumn		träd med snö
COL2A	ShortGreenColumn	litet träd
COL6A	SkullColumn		stort träd
//POL2A	HeadsOnAStick		stort buskigt träd


*/

script "TE_WeatherRain" (VOID)
{
	//SetActivator(0, AAPTR_PLAYER1);;
	//SetActivator(WTHR);
	//if(!SetActivator(0, AAPTR_PLAYER1))
	for(int j = 0; j < MAX_PLAYERS;  j++) // 64 maxplayers in zandronum
    {
		if (PlayerInGame(j))
		{
			SetActivatorToPlayer(j);   
			break;
		}

    }
	
	int uid1 = UniqueTID();
	
	SpawnProjectile(0, "WEATHEREFFECT", 0, 0, 0, 0, uid1);
	SetPointer(AAPTR_MASTER, 0, uid1);
	
	while (TRUE)
	{
		int intensity = 3;//GetCVar("TE_Weather");
		for (int i=0;i < (intensity*9);i++)
		{
			int x = GetActorX(0)+random(-1300.0,1300.0);
			int y = GetActorY(0)+random(-1300.0,1300.0);
			int z = GetActorZ(0)+800.0;
			
			SetActorPosition(uid1, x, y, 5, FALSE);
			int sectorheight = GetActorCeilingZ(uid1);
			if (sectorheight < z)
			{
			z = sectorheight-5.0;
			}
			
			SetActorPosition(uid1, x, y, z, FALSE);
			
			if (CheckActorCeilingTexture(uid1, "F_SKY1"))
			{
				//Log(s:"Raindrops keep fallin on my head..."); 
				SpawnProjectile(uid1, "TE_RainDrop", 0, 0, -120, 0, 0);
			}
		}
		delay(1);
	}
}

script "TE_WeatherSnow" (VOID)
{
	//SetActivator(0, AAPTR_PLAYER1);
	//SetActivator(WTHR);
	for(int j = 0; j < MAX_PLAYERS;  j++) // 64 maxplayers in zandronum
    {
		if (PlayerInGame(j))
		{
			SetActivatorToPlayer(j);   
			break;
		}

    }
	
	int uid1 = UniqueTID();
	
	SpawnProjectile(0, "WEATHEREFFECT", 0, 0, 0, 0, uid1);
	SetPointer(AAPTR_MASTER, 0, uid1);
	
	while (TRUE)
	{
		int intensity = 3;//GetCVar("TE_Weather");
		for (int i=0;i < (intensity*6);i++)
		{
			int x = GetActorX(0)+random(-1300.0,1300.0);
			int y = GetActorY(0)+random(-1300.0,1300.0);
			int z = GetActorZ(0)+800.0;
			
			SetActorPosition(uid1, x, y, 5, FALSE);
			int sectorheight = GetActorCeilingZ(uid1);
			if (sectorheight < z)
			{
			z = sectorheight-5.0;
			}
			
			SetActorPosition(uid1, x, y, z, FALSE);
			
			if (CheckActorCeilingTexture(uid1, "F_SKY1"))
			{
				//Log(s:"Let it snow!"); 
				SpawnProjectile(uid1, "TE_Snowflake", random(0,360), random(0,5), random(-15,-25), 0, 0);
			}
		}
		delay(1);
	}
}

script "EviSplash" (VOID)//Check if on a liquid surface.
// 1 = water
// 2 = nukage
// 3 = blood
// 4 = lava
// 5 = slime
// 0 = default
{
	if (CheckActorFloorTexture(0, "FWATER1")){SetResultValue(1);}
	else if (CheckActorFloorTexture(0, "FWATER2")){SetResultValue(1);}
	else if (CheckActorFloorTexture(0, "FWATER3")){SetResultValue(1);}
	else if (CheckActorFloorTexture(0, "FWATER4")){SetResultValue(1);}
	else if (CheckActorFloorTexture(0, "OGOOPY01")){SetResultValue(1);}
	else if (CheckActorFloorTexture(0, "OICYWA01")){SetResultValue(1);}
	else if (CheckActorFloorTexture(0, "OWATER01")){SetResultValue(1);}
	
	else if (CheckActorFloorTexture(0, "NUKAGE1")){SetResultValue(2);}
	else if (CheckActorFloorTexture(0, "NUKAGE2")){SetResultValue(2);}
	else if (CheckActorFloorTexture(0, "NUKAGE3")){SetResultValue(2);}
	else if (CheckActorFloorTexture(0, "NUKAGE4")){SetResultValue(2);}
	else if (CheckActorFloorTexture(0, "ONUKEA01")){SetResultValue(2);}
	
	else if (CheckActorFloorTexture(0, "BLOOD1")){SetResultValue(3);}
	else if (CheckActorFloorTexture(0, "BLOOD2")){SetResultValue(3);}
	else if (CheckActorFloorTexture(0, "BLOOD3")){SetResultValue(3);}
	else if (CheckActorFloorTexture(0, "BLOOD4")){SetResultValue(3);}
	else if (CheckActorFloorTexture(0, "OBLODA01")){SetResultValue(3);}
	
	else if (CheckActorFloorTexture(0, "LAVA1")){SetResultValue(4);}
	else if (CheckActorFloorTexture(0, "LAVA2")){SetResultValue(4);}
	else if (CheckActorFloorTexture(0, "LAVA3")){SetResultValue(4);}
	else if (CheckActorFloorTexture(0, "LAVA4")){SetResultValue(4);}
	else if (CheckActorFloorTexture(0, "SLIME09")){SetResultValue(4);}
	else if (CheckActorFloorTexture(0, "SLIME10")){SetResultValue(4);}
	else if (CheckActorFloorTexture(0, "SLIME11")){SetResultValue(4);}
	else if (CheckActorFloorTexture(0, "SLIME12")){SetResultValue(4);}
	else if (CheckActorFloorTexture(0, "LAVAFL")){SetResultValue(4);}
	else if (CheckActorFloorTexture(0, "OLAVAC01")){SetResultValue(4);}
	else if (CheckActorFloorTexture(0, "OLAVAD01")){SetResultValue(4);}
	
	else if (CheckActorFloorTexture(0, "SLIME01")){SetResultValue(5);}
	else if (CheckActorFloorTexture(0, "SLIME02")){SetResultValue(5);}
	else if (CheckActorFloorTexture(0, "SLIME03")){SetResultValue(5);}
	else if (CheckActorFloorTexture(0, "SLIME04")){SetResultValue(5);}
	else if (CheckActorFloorTexture(0, "SLIME05")){SetResultValue(5);}
	else if (CheckActorFloorTexture(0, "SLIME06")){SetResultValue(5);}
	else if (CheckActorFloorTexture(0, "SLIME07")){SetResultValue(5);}
	else if (CheckActorFloorTexture(0, "SLIME08")){SetResultValue(5);}
	else if (CheckActorFloorTexture(0, "OTAR__01")){SetResultValue(5);}
	else if (CheckActorFloorTexture(0, "OSLUDG01")){SetResultValue(5);}
	else {SetResultValue(0);}
}