//All pain screen effects.

script "BloodSplashRed" (void) CLIENTSIDE
{
	int Anim;
	int Type = BDCVarInfo[PlayerNumber()].bd_ScreenFX;
	Switch(Type)
	{
		Case 0: Anim = random(580, 585); break;
        Case 1: Anim = random(680, 681); break;
		Default:
        Case 2: delay(1); terminate; break;
	}
	/*if (BDCVarInfo[PlayerNumber()].bd_ScreenFX == 0)
	{
		Anim = random(580, 585);
	}
	else if (BDCVarInfo[PlayerNumber()].bd_ScreenFX == 1)
	{
		Anim = random(680, 681);
	}
	else terminate;*/
	
	ACS_Execute(Anim,0,0,0,0);
}

script "BloodSplashBlue" (void) CLIENTSIDE
{
	int Anim;
	int Type = BDCVarInfo[PlayerNumber()].bd_ScreenFX;
	Switch(Type)
	{
		Case 0: Anim = random(570, 575); break;
        Case 1: Anim = 683; break;
		Default:
        Case 2: delay(1); terminate; break;
	}
	/*if (BDCVarInfo[PlayerNumber()].bd_ScreenFX == 0)
	{
		Anim = random(570, 575);
	}
	else if (BDCVarInfo[PlayerNumber()].bd_ScreenFX == 1)
	{
		Anim = 683;
	}
	else terminate;*/
	
	ACS_Execute(Anim,0,0,0,0);
}

script "BloodSplashGreen" (void) CLIENTSIDE
{
	int Anim;
	int Type = BDCVarInfo[PlayerNumber()].bd_ScreenFX;
	Switch(Type)
	{
		Case 0: Anim = random(560, 565); break;
        Case 1: Anim = 682; break;
		Default:
        Case 2: delay(1); terminate; break;
	}
	/*if (BDCVarInfo[PlayerNumber()].bd_ScreenFX == 0)
	{
		Anim = random(560, 565);
	}
	else if (BDCVarInfo[PlayerNumber()].bd_ScreenFX == 1)
	{
		Anim = 682;
	}
	else terminate;*/
	
	ACS_Execute(Anim,0,0,0,0);
}

script "BloodSplashPurple" (void) CLIENTSIDE
{
	int Anim;
	int Type = BDCVarInfo[PlayerNumber()].bd_ScreenFX;
	Switch(Type)
	{
		Case 0: Anim = random(590, 595); break;
        Case 1: Anim = 686; break;
		Default:
        Case 2: delay(1); terminate; break;
	}
	/*if (BDCVarInfo[PlayerNumber()].bd_ScreenFX == 0)
	{
		Anim = random(590, 595);
	}
	else if (BDCVarInfo[PlayerNumber()].bd_ScreenFX == 1)
	{
		Anim = 686;
	}
	else terminate;*/
	
	ACS_Execute(Anim,0,0,0,0);
}

//This is for the BDv21 BloodSplashes

script 680 (void) CLIENTSIDE
{
	delay(1);
	int ranx = random (0.4, 1.0);
	int rany = random (0.4, 1.0);
	int ran2x = random (0.0, 1.0);
	int ran2y = random (0.0, 1.0);
	setfont("1RBLD1");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, ranx, rany, 1.0);
	setfont("1RBLD2");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, ran2x, ran2y, 1.0);
}	

script 681 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);		
	delay(1);
	
	int ranx = random (2.0, 400.0);
	int rany = random (2.0, 250.0);
	int ran2x = random (2.0, 400.0);
	int ran2y = random (2.0, 250.0);
	setfont("1RBLD1");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, ranx, rany, 1.0);
	setfont("1RBLD2");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, ran2x, ran2y, 1.0);
}

script 682 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(1);
	
	int ranx = random (2.0, 400.0);
	int rany = random (2.0, 250.0);
	int ran2x = random (2.0, 400.0);
	int ran2y = random (2.0, 250.0);
	setfont("1GBLD1");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, ranx, rany, 1.0);
	setfont("1GBLD2");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, ran2x, ran2y, 1.0);
}

script 683 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(1);
	
	int ranx = random (2.0, 400.0);
	int rany = random (2.0, 250.0);
	int ran2x = random (2.0, 400.0);
	int ran2y = random (2.0, 250.0);
	setfont("1BBLD1");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, ranx, rany, 1.0);
	setfont("1BBLD2");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, ran2x, ran2y, 1.0);
}

script 686 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(1);
	
	int ranx = random (2.0, 400.0);
	int rany = random (2.0, 250.0);
	int ran2x = random (2.0, 400.0);
	int ran2y = random (2.0, 250.0);
	setfont("1PBLD1");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, ranx, rany, 1.0);
	setfont("1PBLD2");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, ran2x, ran2y, 1.0);
}

// Pain effects by Sergeant_Mark_IV
// Graphics can be found inside Bleed.wad

script 530 (void)
{
	if(BDCVarInfo[PlayerNumber()].bd_ScreenFX == 2) terminate;
	SetHudSize(320,200,1);
	delay(1);
	
	setfont("PAIN1");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 150.0, 100.0, 0.5);
	delay(4);
}


script 531 (void)
{
	if(BDCVarInfo[PlayerNumber()].bd_ScreenFX == 2) terminate;
	SetHudSize(320,200,1);
	delay(1);
	
	setfont("BREAK1");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 150.0, 100.0, 0.6);
	delay(8);
	
	setfont("BREAK2");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 150.0, 100.0, 0.5);
	delay(3);
}


script 532 (void)
{
	if(BDCVarInfo[PlayerNumber()].bd_ScreenFX == 2) terminate;
	SetHudSize(320,200,1);
	delay(1);
	
	setfont("BREAKS");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 150.0, 100.0, 1.0);
	delay(10);
}


script 533 (void)
{
	if(BDCVarInfo[PlayerNumber()].bd_ScreenFX == 2) terminate;
	SetHudSize(320,200,1);
	delay(1);
	setfont("XBREAK");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 150.0, 100.0, 4.0);
	delay(50);
}


script 611 (void)
{
	if(BDCVarInfo[PlayerNumber()].bd_ScreenFX == 2) terminate;
	SetHudSize(480,300,1);
	delay(1);
	
	setfont("PBULA1");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
	
	setfont("PBULA2");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
	
	setfont("PBULA3");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
}


script 612 (void)
{
	if(BDCVarInfo[PlayerNumber()].bd_ScreenFX == 2) terminate;
	SetHudSize(480,300,1);
	delay(1);
	
	setfont("PBULB1");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
	
	setfont("PBULB2");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
	
	setfont("PBULB3");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
}


script 613 (void)
{
	if(BDCVarInfo[PlayerNumber()].bd_ScreenFX == 2) terminate;
	SetHudSize(480,300,1);
	delay(1);
	
	setfont("PBULC1");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
	
	setfont("PBULC2");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
	
	setfont("PBULC3");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
}

script 614 (void)
{
	if(BDCVarInfo[PlayerNumber()].bd_ScreenFX == 2) terminate;
	SetHudSize(480,300,1);
	delay(1);
	
	setfont("PBULD1");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
	
	setfont("PBULD2");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
	
	setfont("PBULD3");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
}

script 615 (void)
{
	if(BDCVarInfo[PlayerNumber()].bd_ScreenFX == 2) terminate;
	SetHudSize(480,300,1);
	delay(1);
	
	setfont("PBULE1");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
	
	setfont("PBULE2");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
	
	setfont("PBULE3");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
}


script 616 (void)
{
	if(BDCVarInfo[PlayerNumber()].bd_ScreenFX == 2) terminate;
	SetHudSize(480,300,1);
	delay(1);
	
	setfont("PBULF1");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
	
	setfont("PBULF2");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
	
	setfont("PBULF3");
	hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 200.0, 100.0, 0.5);
	delay(8);
}


script 617 (void)
{
	if(BDCVarInfo[PlayerNumber()].bd_ScreenFX == 2) terminate;
	SetHudSize(400,250,1);
	delay(4);
	
	setfont("SCRATCH");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 113.1, 11.1, 0.2);
	delay(4);
}

//WATER
script 684 (void) CLIENTSIDE
{
	if (BDCVarInfo[PlayerNumber()].bd_ScreenFX < 2)
	{
		SetHudSize(400,250,1);
		delay(1);
		
		int ranx = random (200.0, 300.0);
		int rany = random (2.0, 50.0);
		setfont("WTSP");
		hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, ranx, rany, 1.0);
	}
}

// Red Blood dripping on screen by Sergeant_Mark_IV
// Dripping blood graphics can be found inside Bleed.wad

script 580 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(1);
	
	setfont("RBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 63.1, 61.1, 0.3);
	delay(4);
	
	setfont("RBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 63.1, 61.1, 0.3);
	delay(4);
	
	setfont("RBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 63.1, 61.1, 0.3);
	delay(4);
	
	setfont("RBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 63.1, 61.1, 0.3);
	delay(4);
	
	setfont("RBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 63.1, 61.1, 0.3);
	delay(4);
	
	setfont("RBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 63.1, 61.1, 0.3);
	delay(4);
	
	setfont("RBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 63.9, 61.9, 0.3);
	delay(4);
	
	setfont("RBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 63.9, 61.9, 0.3);
	delay(4);
	
	setfont("RBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 63.9, 61.9, 0.3);
	delay(4);
	
	setfont("RBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 63.9, 61.9, 0.3);
	delay(4);
	
	setfont("RBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 63.9, 61.9, 0.3);
	delay(4);
}

script 581 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(2);
	
	setfont("RBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("RBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("RBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("RBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("RBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("RBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("RBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("RBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("RBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("RBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("RBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
}

script 582 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(3);
	
	setfont("RBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.2);
	delay(4);
	
	setfont("RBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("RBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("RBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("RBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("RBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("RBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
	
	setfont("RBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
	
	setfont("RBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
	
	setfont("RBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
	
	setfont("RBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
}

script 583 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(4);
	
	setfont("RBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.2);
	delay(4);
	
	setfont("RBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("RBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("RBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("RBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("RBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("RBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
	
	setfont("RBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
	
	setfont("RBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
	
	setfont("RBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
	
	setfont("RBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
}

script 584 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(4);
	
	setfont("RBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.2);
	delay(4);
	
	setfont("RBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("RBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("RBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("RBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("RBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("RBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
	
	setfont("RBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
	
	setfont("RBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
	
	setfont("RBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
	
	setfont("RBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
}


script 585 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(4);
	
	setfont("RBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.2);
	delay(4);
	
	setfont("RBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("RBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("RBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("RBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("RBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("RBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
	
	setfont("RBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
	
	setfont("RBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
	
	setfont("RBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
	
	setfont("RBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
}

// Blue Blood dripping on screen by Sergeant_Mark_IV
// Dripping blood graphics can be found inside Bleed.wad

script 570 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(1);
	
	setfont("BBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("BBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("BBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("BBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("BBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("BBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("BBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("BBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("BBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("BBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("BBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
}

script 571 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(2);
	
	setfont("BBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("BBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("BBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("BBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("BBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("BBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("BBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("BBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("BBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("BBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("BBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
}

script 572 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(3);
	
	setfont("BBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.2);
	delay(4);
	
	setfont("BBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("BBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("BBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("BBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("BBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("BBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
	
	setfont("BBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
	
	setfont("BBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
	
	setfont("BBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
	
	setfont("BBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
}

script 573 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(4);
	
	setfont("BBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.2);
	delay(4);
	
	setfont("BBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("BBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("BBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("BBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("BBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("BBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
	
	setfont("BBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
	
	setfont("BBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
	
	setfont("BBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
	
	setfont("BBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
}



script 574 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(4);
	
	setfont("BBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.2);
	delay(4);
	
	setfont("BBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("BBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("BBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("BBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("BBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("BBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
	
	setfont("BBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
	
	setfont("BBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
	
	setfont("BBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
	
	setfont("BBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
}


script 575 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(4);
	
	setfont("BBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.2);
	delay(4);
	
	setfont("BBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("BBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("BBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("BBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("BBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("BBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
	
	setfont("BBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
	
	setfont("BBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
	
	setfont("BBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
	
	setfont("BBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
}

// Green Blood dripping on screen by Sergeant_Mark_IV
// Dripping blood graphics can be found inside Bleed.wad

script 560 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(1);
	
	setfont("GBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("GBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("GBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("GBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("GBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("GBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("GBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("GBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("GBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("GBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("GBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);	
}

script 561 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(2);
	
	setfont("GBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("GBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("GBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("GBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("GBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("GBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("GBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("GBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("GBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("GBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("GBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
}

script 562 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(3);
	
	setfont("GBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.2);
	delay(4);
	
	setfont("GBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("GBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("GBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("GBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("GBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("GBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
	
	setfont("GBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
	
	setfont("GBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
	
	setfont("GBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
	
	setfont("GBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
}

script 563 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(4);
	
	setfont("GBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.2);
	delay(4);
	
	setfont("GBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("GBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("GBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("GBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("GBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("GBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
	
	setfont("GBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
	
	setfont("GBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
	
	setfont("GBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
	
	setfont("GBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
}



script 564 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(4);
	
	setfont("GBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.2);
	delay(4);
	
	setfont("GBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("GBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("GBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("GBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("GBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("GBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
	
	setfont("GBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
	
	setfont("GBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
	
	setfont("GBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
	
	setfont("GBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
}


script 565 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(4);
	
	setfont("GBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.2);
	delay(4);
	
	setfont("GBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("GBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("GBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("GBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("GBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("GBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
	
	setfont("GBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
	
	setfont("GBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
	
	setfont("GBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
	
	setfont("GBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
}

// Purple Blood dripping on screen by Sergeant_Mark_IV
// Dripping blood graphics can be found inside Bleed.wad

script 590 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(1);
	
	setfont("PBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("PBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("PBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("PBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("PBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("PBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("PBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("PBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("PBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("PBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
	
	setfont("PBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
	delay(4);
}

script 591 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(2);
	
	setfont("PBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("PBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("PBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("PBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("PBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("PBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("PBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("PBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("PBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("PBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
	
	setfont("PBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
	delay(4);
}

script 592 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(3);
	
	setfont("PBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.2);
	delay(4);
	
	setfont("PBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("PBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("PBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("PBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("PBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
	delay(4);
	
	setfont("PBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
	
	setfont("PBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
	
	setfont("PBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
	
	setfont("PBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
	
	setfont("PBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
	delay(4);
}

script 593 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(4);
	
	setfont("PBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.2);
	delay(4);
	
	setfont("PBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("PBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("PBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("PBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("PBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
	delay(4);
	
	setfont("PBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
	
	setfont("PBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
	
	setfont("PBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
	
	setfont("PBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
	
	setfont("PBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
	delay(4);
}



script 594 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(4);
	
	setfont("PBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.2);
	delay(4);
	
	setfont("PBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("PBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("PBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("PBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("PBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
	delay(4);
	
	setfont("PBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
	
	setfont("PBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
	
	setfont("PBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
	
	setfont("PBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
	
	setfont("PBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
	delay(4);
}


script 595 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(4);
	
	setfont("PBLD1");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.2);
	delay(4);
	
	setfont("PBLD2");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("PBLD3");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("PBLD4");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("PBLD5");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("PBLD6");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
	delay(4);
	
	setfont("PBLD7");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
	
	setfont("PBLD8");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
	
	setfont("PBLD9");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
	
	setfont("PBLD10");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
	
	setfont("PBLD11");
	hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
	delay(4);
}

/*script "Hate_Effect" (void) CLIENTSIDE
{
	if(BDCVarInfo[PlayerNumber()].bd_ScreenFX == 2 || CheckInventory("IsPlayer")== 0) 
		terminate;	
	
	delay(1);
	
	setfont("HATEFX");
	SetHudSize(320, 200, TRUE);
    HudMessage(s:"A"; HUDMSG_FADEINOUT, 0, CR_UNTRANSLATED, 320.0, 100.0, 1.0, 1.0, 0.0);
	delay(70);
	
	if(CheckInventory("HateAttackHit") == 1){
		hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 320.0, 100.0, 1.4);
		TakeInventory("HateAttackHit",0x7FFFFFFF);
	}
	else{ 
		hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 320.0, 100.0, 0.1);
	}
}*/

#define ticrate 35

script "Hate_Effect" (void) CLIENTSIDE
{
	if(BDCVarInfo[PlayerNumber()].bd_ScreenFX == 2 || CheckInventory("IsPlayer")== 0) 
		terminate;	
	
	delay(1);
		//TakeInventory("HateImminent",0x7FFFFFFF);
	
	setfont("HATEFX");
	SetHudSize(320, 200, TRUE);
	HudMessage(s:"A"; HUDMSG_FADEINOUT, 0, CR_UNTRANSLATED, 320.0, 100.0, (1.0 / 35) * 6, (1.0 / 35) * 8, 0.0);
	delay(12);
	
	int ticAmount = 13;
	int HateImminent = (1.0 / ticrate) * ticAmount;
	//int HateImminent = (1.0 / 35) * 13;
	
	if(CheckInventory("HateImminent") > 0)
	{
		HudMessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 320.0, 100.0, HateImminent);
		delay(12);
	}
	if(CheckInventory("HateImminent") > 1)
	{
		HudMessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 320.0, 100.0, HateImminent);
		delay(12);
	}
	if(CheckInventory("HateImminent") > 2)
	{
		HudMessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 320.0, 100.0, HateImminent);
		delay(12);
	}
	if(CheckInventory("HateImminent") > 3)
	{
		HudMessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 320.0, 100.0, HateImminent);
		delay(12);
	}

	if(CheckInventory("HateAttackHit") == 1){
		//int Breaks = random(531, 533);
		ACS_Execute(531,0,0,0,0);
		hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 320.0, 100.0, 1.4);
		TakeInventory("HateImminent",0x7FFFFFFF);
		TakeInventory("HateAttackHit",0x7FFFFFFF);
		delay(1);
	}
	else{ 
		hudmessage(s:"A"; HUDMSG_FADEOUT, 0, CR_UNTRANSLATED, 320.0, 100.0, 0.4);
		TakeInventory("HateImminent",0x7FFFFFFF);
	}
}
