
// Purple Blood dripping on screen by Sergeant_Mark_IV
// Dripping blood graphics can be found inside Bleed.wad

script 580 (void) CLIENTSIDE
{
	if (bd_ScreenFX == 0)
	{
		SetHudSize(400,250,1);
		delay(1);
		
		setfont("PBLD1");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
		delay(4);
		
		setfont("PBLD2");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
		delay(4);
		
		setfont("PBLD3");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
		delay(4);
		
		setfont("PBLD4");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
		delay(4);
		
		setfont("PBLD5");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
		delay(4);
		
		setfont("PBLD6");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
		delay(4);
		
		setfont("PBLD7");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
		delay(4);
		
		setfont("PBLD8");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
		delay(4);
		
		setfont("PBLD9");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
		delay(4);
		
		setfont("PBLD10");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
		delay(4);
		
		setfont("PBLD11");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 73.1, 71.1, 0.3);
		delay(4);
	}	
	
	if (bd_ScreenFX == 1)
	{
		ACS_Execute(683, 0, 0, 0, 0);
	}
}

script 581 (void) CLIENTSIDE
{
	if (bd_ScreenFX == 0)
	{
		SetHudSize(400,250,1);
		delay(2);
		
		setfont("PBLD1");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
		delay(4);
		
		setfont("PBLD2");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
		delay(4);
		
		setfont("PBLD3");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
		delay(4);
		
		setfont("PBLD4");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
		delay(4);
		
		setfont("PBLD5");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
		delay(4);
		
		setfont("PBLD6");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
		delay(4);
		
		setfont("PBLD7");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
		delay(4);
		
		setfont("PBLD8");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
		delay(4);
		
		setfont("PBLD9");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
		delay(4);
		
		setfont("PBLD10");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
		delay(4);
		
		setfont("PBLD11");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 0.9, 30.9, 0.3);
		delay(4);
	}
}

script 582 (void) CLIENTSIDE
{
	if (bd_ScreenFX == 0)
	{
		SetHudSize(400,250,1);
		delay(3);
		
		setfont("PBLD1");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.2);
		delay(4);
		
		setfont("PBLD2");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
		delay(4);
		
		setfont("PBLD3");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
		delay(4);
		
		setfont("PBLD4");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
		delay(4);
		
		setfont("PBLD5");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
		delay(4);
		
		setfont("PBLD6");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.1, 81.1, 0.3);
		delay(4);
		
		setfont("PBLD7");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
		delay(4);
		
		setfont("PBLD8");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
		delay(4);
		
		setfont("PBLD9");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
		delay(4);
		
		setfont("PBLD10");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
		delay(4);
		
		setfont("PBLD11");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 263.9, 81.9, 0.3);
		delay(4);
	}
}

script 583 (void) CLIENTSIDE
{
	if (bd_ScreenFX == 0)
	{
		SetHudSize(400,250,1);
		delay(4);
		
		setfont("PBLD1");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.2);
		delay(4);
		
		setfont("PBLD2");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
		delay(4);
		
		setfont("PBLD3");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
		delay(4);
		
		setfont("PBLD4");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
		delay(4);
		
		setfont("PBLD5");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
		delay(4);
		
		setfont("PBLD6");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.1, -11.1, 0.3);
		delay(4);
		
		setfont("PBLD7");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
		delay(4);
		
		setfont("PBLD8");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
		delay(4);
		
		setfont("PBLD9");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
		delay(4);
		
		setfont("PBLD10");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
		delay(4);
		
		setfont("PBLD11");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 123.9, -11.9, 0.3);
		delay(4);
	}
}

script 584 (void) CLIENTSIDE
{
	if(bd_ScreenFX == 0)
	{
		SetHudSize(400,250,1);
		delay(4);
		
		setfont("PBLD1");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.2);
		delay(4);
		
		setfont("PBLD2");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
		delay(4);
		
		setfont("PBLD3");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
		delay(4);
		
		setfont("PBLD4");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
		delay(4);
		
		setfont("PBLD5");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
		delay(4);
		
		setfont("PBLD6");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 101.1, 0.3);
		delay(4);
		
		setfont("PBLD7");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
		delay(4);
		
		setfont("PBLD8");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
		delay(4);
		
		setfont("PBLD9");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
		delay(4);
		
		setfont("PBLD10");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
		delay(4);
		
		setfont("PBLD11");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 101.9, 0.3);
		delay(4);
	}
}

script 585 (void) CLIENTSIDE
{
	if (bd_ScreenFX == 0)
	{
		SetHudSize(400,250,1);
		delay(4);
		
		setfont("PBLD1");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.2);
		delay(4);
		
		setfont("PBLD2");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
		delay(4);
		
		setfont("PBLD3");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
		delay(4);
		
		setfont("PBLD4");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
		delay(4);
		
		setfont("PBLD5");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
		delay(4);
		
		setfont("PBLD6");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.1, 11.1, 0.3);
		delay(4);
		
		setfont("PBLD7");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
		delay(4);
		
		setfont("PBLD8");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
		delay(4);
		
		setfont("PBLD9");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
		delay(4);
		
		setfont("PBLD10");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
		delay(4);
		
		setfont("PBLD11");
		hudmessage(s:"A"; HUDMSG_PLAIN, 0, CR_UNTRANSLATED, 213.9, 11.9, 0.3);
		delay(4);
	}
}