enum
{
	GBL_TITLEHASH = -10555,
	GBL_WADCHECK
};

global raw 45:BD_Globals[];

Script "WadChecker"
{
	delay(2);
	static str WadSelect[] =
	{
		"IsANazi", //Doom 2 (Default Nazi)
		"BW", //Doom 2 (Brutal Wolfenstein Nazi)
		"FormerMarine", //Doom 2 (Former Soldiers)
		"Alieni", //Ancient Aliens
		"Eviternity", //Eviternity
		"ScytheII", //Scythe II
		"Resurgence", //Resurgence
		"ReplaceGoingDown", //Going Down
		"IsEpic2Alien", //Epic 2
		"Bloodstain", //Bloodstain
		"TNTRevilution", //TNT Revilution
		"Jenesis", //Jenesis
		"2048Unleashed", //2048 Unleashed
		"DoomZero", //Doom Zero
		"Wormwood", //Wormwood
		"D64D2", //D64D2
		"FormerMarine", //Hellfire: Dreams
		"NERF" //Not Even Remotely Fair
	};
    if(bd_WadCheck > 0)
        SetActorState(0, wadSelect[bd_WadCheck - 1]);
		//Log(s:wadSelect[bd_WadCheck - 1]);
}

int WadHash[] =
{
	//0x0000000, //Doom 2 (Default Nazi)
	//0x0000000, //Doom 2 (Brutal Wolfenstein Nazi)
	//0x0000000, //Doom 2 (Former Soldiers) eday06_2D500005
	0x3706294F, //Ancient Aliens
	0x692F6439, //Eviternity
	0xC244EABF, //Scythe II
	0x52300A40, //Resurgence
	0x497293A6, //Going Down
	0xD303FA02, //Epic 2
	0x42E57B54, //Bloodstain
	0xE76C8502, //TNT Revilution
	0x1FC2CF3E, //Jenesis
	0xDDD6DE16, //2048 Unleashed
	0x31F67187, //Doom Zero
	0xF69D278A, //Wormwood
	0xE7A8E948, //D64D2
	0x77033279, //Hellfire: Dreams
	0x285402AF //Not Even Remotely Fair
};

bool HasLumpReading ()
{
	static int cached = -1;
	if(cached != -1)
		return (bool)cached;

	cached = ZC_LumpOpen("DECORATE");
	if(cached)
		ZC_LumpClose(cached);

	return cached = !!cached;//(int)bool(cached);
}

Script "BD_HashTitlepic" OPEN
{
	int tpic, len, sum;

	enum
	{
		TITLEPIC_MAX = 68500
	};

	if(BD_Globals[GBL_TITLEHASH] != 0)
	{
		bd_WadCheck = BD_Globals[GBL_WADCHECK];
		terminate;
	}
	
	if (!HasLumpReading()) terminate;

    tpic = ZC_LumpOpen("TITLEPIC");

    if(tpic == -1)
        terminate;

    len = ZC_LumpGetInfo(tpic, LUMP_INFO_SIZE);
    len -= len % 4;
    if(len > TITLEPIC_MAX)
		len = TITLEPIC_MAX;

    for(int i = 0; i < len; i += 4)
    {
        sum += ZC_LumpRead(tpic, i, LUMP_READ_INT);
    }

    foreach(let int k, v; WadHash)
    {
        if(sum == v)
        {
			bd_WadCheck = k + 4;
            break;
        }
    }    

    BD_Globals[GBL_TITLEHASH] = sum;
    BD_Globals[GBL_WADCHECK] = bd_WadCheck;
    
    ZC_LumpClose(tpic);
}

script "BD_TitleMapAndWadHashes" ENTER
{
	if(!GetCvar("bd_showtitlemaphash"))
		terminate;
		Log(x:BD_Globals[GBL_TITLEHASH]); // returns wad hash#.
		
	if(!GetCvar("bd_showwadhash"))
		terminate;
		Log(d:bd_WadCheck);	
}
