
Script "PuristSelector"
{
	//delay(1);
	static str Weapons[][] =
	{
		{"BrutalPistol", "PuristPistol"}, {"BrutalSMG", "PuristSMG"}, {"MP40", "PuristMP40"}, 
		{"Revolver", "PuristRevolver"}, {"Shot_Gun", "PuristShot_Gun"}, {"AssaultShotgun", "PuristAssaultShotgun"}, 
		{"SSG", "PuristSSG"}, {"Sniper", "PuristSniper"}, {"Rifle", "PuristRifle"}, 
		{"MiniGun", "PuristMiniGun"}, {"MG42", "PuristMG42"}, {"IncendiaryLauncher", "PuristIncendiaryLauncher"}, 
		{"GrenadeLauncher", "PuristGrenadeLauncher"}, {"Rocket_Launcher", "PuristRocket_Launcher"}, {"Devastator", "PuristDevastator"}, 
		{"Plasma_Gun", "PuristPlasma_Gun"}, {"RailGun", "PuristRailGun"}, {"NukeLauncher", "PuristNukeLauncher"}, 
		{"BFG10k", "PuristBFG10k"}, {"BIG_FUCKING_GUN", "PuristBIG_FUCKING_GUN"}, {"HellishMissileLauncher", "PuristHellishMissileLauncher"}, 
		{"Unmaker", "PuristUnmaker"}, {"FlameCannon", "PuristFlameCannon"}, {"Flamethrower2", "PuristFlamethrower2"}, 
		{"HandGrenades", "PuristHandGrenades"}
	};
		
	str currWpn = GetWeapon();
	str wpnToSet = currWpn;
	
	foreach(let auto wpn; Weapons)
	{
		if(StrICmp(currWpn, wpn[0]) == 0)
		{
			wpnToSet = wpn[1];
			GiveInventory(wpnToSet, 1);
			break;
		}
	}
	
	if(StrICmp(currWpn, wpnToSet) == 0) terminate;
    SetWeapon(wpnToSet); 
	delay(1);
    TakeInventory(currWpn, 1);
}

Script "PuristRemover"
{
	delay(1);
	static str Weapons[][] =
	{
		{"BrutalPistol", "PuristPistol"}, {"BrutalSMG", "PuristSMG"}, {"MP40", "PuristMP40"}, 
		{"Revolver", "PuristRevolver"}, {"Shot_Gun", "PuristShot_Gun"}, {"AssaultShotgun", "PuristAssaultShotgun"}, 
		{"SSG", "PuristSSG"}, {"Sniper", "PuristSniper"}, {"Rifle", "PuristRifle"}, 
		{"MiniGun", "PuristMiniGun"}, {"MG42", "PuristMG42"}, {"IncendiaryLauncher", "PuristIncendiaryLauncher"}, 
		{"GrenadeLauncher", "PuristGrenadeLauncher"}, {"Rocket_Launcher", "PuristRocket_Launcher"}, {"Devastator", "PuristDevastator"}, 
		{"Plasma_Gun", "PuristPlasma_Gun"}, {"RailGun", "PuristRailGun"}, {"NukeLauncher", "PuristNukeLauncher"}, 
		{"BFG10k", "PuristBFG10k"}, {"BIG_FUCKING_GUN", "PuristBIG_FUCKING_GUN"}, {"HellishMissileLauncher", "PuristHellishMissileLauncher"}, 
		{"Unmaker", "PuristUnmaker"}, {"FlameCannon", "PuristFlameCannon"}, {"Flamethrower2", "PuristFlamethrower2"}, 
		{"HandGrenades", "PuristHandGrenades"}
	};
		
	str wpnToTake;
	
	foreach(let auto wpn; Weapons)
	{
		//if(StrICmp(currWpn, wpn[1]) == 0)
		While(CheckInventory(wpn[1]))
		{
			wpnToTake = wpn[0];
			TakeInventory(wpnToTake, 1);
			break;
		}
	}
}